language: javascript
cache:
  directories:
  - node_modules
before_install:
- nvm install && nvm use && nvm version
- npm install yarn
install:
- yarn
script: 
- npm run lint
- npm run test
- cd android && ./gradlew assembleRelease