language: javascript
branches:
  only:
    - master
before_install:
  - nvm install && nvm use
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm run lint
  - npm test
after_script:
  - npm run update-coverage
